'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace E4936


	Partial Public Class [Default]

		''' <summary>
		''' form1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' ReportToolbarOrders control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ReportToolbarOrders As Global.DevExpress.XtraReports.Web.ReportToolbar

		''' <summary>
		''' btSave control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected btSave As Global.DevExpress.Web.ASPxEditors.ASPxButton

		''' <summary>
		''' cbExportFormat control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected cbExportFormat As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

		''' <summary>
		''' ReportViewerOrders control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ReportViewerOrders As Global.DevExpress.XtraReports.Web.ReportViewer

		''' <summary>
		''' lpExporting control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected lpExporting As Global.DevExpress.Web.ASPxLoadingPanel.ASPxLoadingPanel

		''' <summary>
		''' cbExport control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected cbExport As Global.DevExpress.Web.ASPxCallback.ASPxCallback

		''' <summary>
		''' btSaveToResponse control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected btSaveToResponse As Global.DevExpress.Web.ASPxEditors.ASPxButton
	End Class
End Namespace
